#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/makes

###

POST http://localhost:3333/makes
Content-Type: application/json

{
    "tipo": "Batom2",
    "cor": "Vermelho",
    "marca": "Mari Maria"
}

###

PUT http://localhost:3333/makes/id
Content-Type: application/json

{
    "tipo": "Batom",
    "cor": "Vermelho",
    "marca": "Mari Maria"
}

###

DELETE http://localhost:3333/makes/id
